### ISSUE TITLE
Fail to install Server using npm install

### ISSUE THREAD

**Issue by wenkeyang** [dcalsky/jwt-express-react#1]
Can you give a instruction how server and client part work together?  
I using npm install, it always fail in 
node-gyp rebuild, 

also, there is no binding.gyp fail as well.

**Comment by dcalsky** [comment]
I have updated README and relational dependencies, and you can follow README to try again with the `yarn`.

**Comment by dcalsky** [comment]
If you cannot run it correct in any case, you should skip it. Because the key point of this project is simply showing how does this workflow run, rather than using it actually.
